version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/DockerfileFrontend
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/src
      # Don't overwrite node_modules from the build step
      - /src/node_modules
    ports:
      - "3000:3000"
    links:
      - backend
    # depends_on:
    #   - backend

  backend:
    build:
      context: .
      dockerfile: docker/DockerfileBackend
    command: ./gradlew vertxRun
    #command: ./gradlew vertxDebug # development
    environment:
     - VERTX_DEBUG=true
     - MONGO_URI=mongodb://localhost:27017
     - MONGO_USERNAME=graphql
     - MONGO_PASSWORD=yoga123
     - MONGO_DATABASE=graphqldb
     - HTTP_PORT=4000
    # - HTTPS_PORT=4022
    # - HTTPS_KEY=""
    # - HTTPS_CRT=""
    ports:
      - "4000:4000"
    #  - "5005:5005" # development
    volumes:
      - ./backend:/src
      - ./data/log:/var/log:rw
    links:
      - mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:1.12.2-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - FRONTEND_PORT=3000  # development
    volumes:
      - ./config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/ssl
      - ./data/log:/var/log/nginx/:rw
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend

  mongo:
    image: "bitnami/mongodb:latest"
    ports:
      - '27017:27017'
    environment:
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: yoga123
      MONGODB_DATABASE: graphqldb
    volumes:
      - './data/mongo:/data/db'